### ISSUE TITLE
Plex for Android (mobile) has broken playback

### ISSUE THREAD

**Issue by brimur** [taligentx/LiveTVH.bundle#17]
Hi,

Just an FYI as it's not an issue but could be fixable. I'm not sure if it was accidental or intentional but version 6.10 and onward of Plex for Android causes an error in playback using LiveTVH. The channel list is accessible bit playing any of them causes an error "playback stopped"

I created a thread for it on the Plex forum and tagged Plex people but it is being ignored so I'm guessing it was intentional

https://forums.plex.tv/discussion/299097/latest-version-6-10-2-2954-causing-error-playback-has-stopped

**Comment by joohkim88** [comment]
Same thing happens to me.

**Comment by taligentx** [comment]
Let's take a look at the logs and see if there's a useful error - perhaps there's some extra info that's being requested from PMS by the newer versions for Android.

Try to play a file and then pull:

Android logs:
https://support.plex.tv/hc/en-us/articles/201573117-Android-Android-TV-Fire-TV-Logs

LiveTVH logs:
~PMS Plugin Logs/com.plexapp.plugins.livetvh.log

**Comment by brimur** [comment]
Thanks for getting back to us @taligentx 

I looked through the logs and saw that the exo player is throwing an error. When I went into Settings>Advanced>Player and checked the "Use Android Player" the issues was resolved. 

````
12-26 19:32:15.433  i: [DeviceCapabilitiesChangedBehaviour] Recording source codec (unknown) support: false (Passthrough: false)
12-26 19:32:15.456  e: [Exo1VideoPlayer] Error building the renderers: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
	at com.google.android.exoplayer.upstream.j.a(SourceFile:208)
	at com.google.android.exoplayer.upstream.k.a(SourceFile:133)
	at com.google.android.exoplayer.upstream.f.b(SourceFile:96)
	at com.google.android.exoplayer.upstream.f.a(SourceFile:55)
	at com.google.android.exoplayer.upstream.r.h(SourceFile:91)
	at com.google.android.exoplayer.upstream.m.run(SourceFile:222)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

12-26 19:32:15.470  i: [video] Error detected before playback
12-26 19:32:15.510  i: [TranscodeSession] Stopping...
12-26 19:32:15.512  e: [Video Player] A recoverable error occurred while attempting to play
12-26 19:32:15.513  e: [Video Player] Playback has stopped because the connection to the Plex Media Server has been lost. Please ensure the server is available and retry.
12-26 19:32:15.513  i: [Video Player] Showing retry playback dialog.
12-26 19:32:15.515  i: [BufferHelper] Assumed Bitrate: 10000, Segment Count: 1171
12-26 19:32:15.515  i: [BufferHelper] Segment count: 1171
12-26 19:32:15.516  i: [TranscodeSession] Notifying server that we've stopped
````
