### ISSUE TITLE
List channels without thumbnail?

### ISSUE THREAD

**Issue by brimur** [taligentx/LiveTVH.bundle#20]
Hi @taligentx, just curious if would be a small change to the code to list channels without the thumbnail or have the thumbnail on the left and text on the right of it, similar to the views in Plex itself. Thanks

**Comment by taligentx** [comment]
Hi @brimur, if you're referring to the Android client, the view is set by the client app and plugins don't have direct control over how it shows up.  I recommend adding feedback for the client app developers. This is one of several display quirks in the Android app, like the plugins list being displayed with the plugin icons being partially obscured by the plugin's own name.

In the iOS app, the LiveTVH channel list is text-only and there is no way to display a channel list with thumbnails.
