### ISSUE TITLE
Play back only lasts for 10 minutes  

### ISSUE THREAD

**Issue by zerocool9** [taligentx/LiveTVH.bundle#21]
Great plugin all working really well, Apart from when i open a stream in Plex it only lasts 10 minutes then plex closes the connection as if its only a 10min file, How do i increase this or trick plex into thinking its say 5 hours long? cant seem to figure out if this is a problem with my server or on the app its self because i have no idea where i would go to change this on my server

**Comment by taligentx** [comment]
Hi @zerocool9, I'm reviewing the code and Plex plugin framework again to see if there is room for improvement.  The plugin sets the stream length to 24 hours so it should not quit after 10 minutes.

If you would like to continue troubleshooting this issue, post the Plex app and version that you're using, and if the same issue happens through the Plex web client.

**Comment by taligentx** [comment]
Closing, feel free to re-open if you are still running into this issue.
