### ISSUE TITLE
DVB-S/S2

### ISSUE THREAD

**Issue by next2non** [taligentx/LiveTVH.bundle#5]
Hi 

I did some testing and found out that IPTV channels work fine on LiveTV (streaming both audio and video), but DVB-S/S2 channels do not stream (both HD and SD channels). They establish a connection with TVheadend but immediately drops (as seen from TVheadend log).

Issue with with DVB-S/S2 channels not being able to stream using LiveTV.

Regards,
Tariq

P.S. i posted this in plex forum as well

**Comment by taligentx** [comment]
Hi Tariq,

See if this issue occurs with the current 1.2 release after you set the channel tags in Tvheadend for the codec of each channel.  If so, grab the LiveTVH and Plex client logs - thanks!

-Nikhil

**Comment by next2non** [comment]
Hi Nikhil

I have tested the new release 1.2 and the same issue. IPTV streams fine one DVB-S/S2 channels do not stream (Both HD and SD channels). Attaching required logs, hope it helps

[Plex Log.zip](https://github.com/taligentx/LiveTVH.bundle/files/1022158/Plex.Log.zip)

**Comment by taligentx** [comment]
Gotcha, which video and audio codecs are used on the DVB-S and S2 channels?

iOS is seeing an HTTP 404 error when it attempts to play from the server:

`<AVPlayerItemErrorLogEvent:0x17420d750 date=2017-05-23 12:42:22 +0000 URI=(null) serverAddress=(null) playbackSessionID=73392E61-523D-48AF-B25C-F8465C3056D0 errorStatusCode=-12938 errorDomain=CoreMediaErrorDomain errorComment=HTTP 404: File Not Found>`

Try playing from iOS again and pulling `Plex Media Server.log` from PMS itself - it looks like there may be something else going on.

**Comment by next2non** [comment]
Mostly are either MPEG-2 and MPEG-4
[PMS Log.zip](https://github.com/taligentx/LiveTVH.bundle/files/1023135/PMS.Log.zip)

**Comment by taligentx** [comment]
Hi Tariq, the link is broken - can you attach it again?

**Comment by next2non** [comment]
Uploaded again

[PMS Log.zip](https://github.com/taligentx/LiveTVH.bundle/files/1024022/PMS.Log.zip)

**Comment by next2non** [comment]
Hi Nikhil 

Managed to make it work. Had to add tags to the channels for SD MPEG2 and for HD MPEG-4/HD and now everything is working fine. 

Thanks for the support.

Regards
Tariq

**Comment by taligentx** [comment]
Hi Tariq, that's good to hear as I wasn't seeing the problem in the logs.  Thanks for the update!

**Comment by next2non** [comment]
Tariq Mirza liked your email
Spark by Readdle
