### ISSUE TITLE
Pagination lacks a back entry

### ISSUE THREAD

**Issue by mastacheata** [taligentx/LiveTVH.bundle#8]
You added the Next button at the end of the page if there are more elements to come, but you forgot the entry at the top to go back.

**Comment by taligentx** [comment]
Hi, which Plex client is missing back navigation?  The Plex framework doesn't define a PreviousPageObject as there should be back navigation built into the client (at least on PMP, OpenPHT, Web, iOS, Android).

**Comment by mastacheata** [comment]
Ahh, you mean you can use the default back button?
I didn't think about that at all.
Always thought of it as a one-level-up button.
